import os


def writeObj(triangles, path):
    """Write one flat Vector3 triangle list (3 per triangle) to an OBJ
    file. No vertex deduplication or normals - OBJ doesn't require either,
    and viewers/slicers derive normals from face winding anyway."""
    with open(path, "w") as f:
        f.write("# Generated by Plate-A-Pixel\n")
        for v in triangles:
            f.write(f"v {v.x} {v.y} {v.z}\n")
        for i in range(0, len(triangles), 3):
            # OBJ face indices are 1-based.
            f.write(f"f {i + 1} {i + 2} {i + 3}\n")


def exportMeshObjs(mesh, outputDir, baseName="pixelart"):
    """Write one OBJ file per disconnected component in mesh.meshes (a
    color rarely ends up as a single physically connected piece - see
    Mesh.warnings), plus one for the base plate (mesh.baseMesh). Returns
    the list of file paths written."""
    os.makedirs(outputDir, exist_ok=True)

    paths = []
    for colorIndex, components in enumerate(mesh.meshes):
        for partIndex, triangles in enumerate(components):
            if not triangles:
                continue
            filename = f"{baseName}_color{colorIndex}_part{partIndex}.obj"
            path = os.path.join(outputDir, filename)
            writeObj(triangles, path)
            paths.append(path)

    for partIndex, triangles in enumerate(mesh.baseMesh):
        if not triangles:
            continue
        filename = f"{baseName}_base_part{partIndex}.obj"
        path = os.path.join(outputDir, filename)
        writeObj(triangles, path)
        paths.append(path)

    return paths
