import os

# OBJ has no field for units at all - no header, no declaration, nothing a
# slicer can read. Coordinates are just numbers. A slicer's "inches or mm?"
# prompt is a heuristic off the bounding box size: a 1-unit-wide pixel cell
# looks implausibly tiny as millimeters but plausible as inches. The only
# real fix is baking a physical size into the coordinates themselves, so
# they're unambiguous - MM_PER_UNIT is how many millimeters one world unit
# (one pixel cell) becomes on export.
MM_PER_UNIT = 10.0


def writeObj(triangles, path, cellWidth=MM_PER_UNIT, cellHeight=MM_PER_UNIT):
    """Write one (N, 3) triangle-soup array (3 rows per triangle) to an
    OBJ file, scaling coordinates (world units -> millimeters) on the way
    out. cellWidth scales X and Z (a pixel's footprint), cellHeight scales
    Y (one height-layer's thickness) - the two are independent since a
    print's pixels needn't be cubes. No vertex deduplication or normals -
    OBJ doesn't require either, and viewers/slicers derive normals from
    face winding anyway."""
    with open(path, "w") as f:
        f.write("# Generated by Plate-A-Pixel\n")
        f.write(f"# Units: millimeters ({cellWidth}mm per cell, {cellHeight}mm per layer)\n")
        # .tolist() once: iterating the numpy array row-by-row would
        # otherwise box a numpy scalar for every single x/y/z.
        for x, y, z in triangles.tolist():
            f.write(f"v {x * cellWidth} {y * cellHeight} {z * cellWidth}\n")
        for i in range(0, len(triangles), 3):
            # OBJ face indices are 1-based.
            f.write(f"f {i + 1} {i + 2} {i + 3}\n")


def unnamedColorIndices(palette):
    """Palette indices with no name set. Export names each printed part
    after its color's layer name (see exportMeshObjs) - an unnamed color
    would produce a meaningless "_partN.obj" filename, so both the save
    guard and the export flow check this before doing anything (see
    MenuBar._blockedByUnnamedColors and the export window)."""
    return [i for i, entry in enumerate(palette) if not entry.name]


def duplicateColorNames(palette):
    """Names shared by more than one palette entry - since export now
    writes every part flat into one folder (no per-color subfolder),
    two colors with the same name would silently overwrite each other's
    files."""
    counts = {}
    for entry in palette:
        if entry.name:
            counts[entry.name] = counts.get(entry.name, 0) + 1
    return sorted(name for name, count in counts.items() if count > 1)


def exportMeshObjs(mesh, outputDir, cellWidth=MM_PER_UNIT, cellHeight=MM_PER_UNIT):
    """Write one OBJ file per disconnected component in mesh.meshes (a
    color rarely ends up as a single physically connected piece - see
    Mesh.warnings), flat into outputDir - the destination the user
    already named via the export window, so this doesn't invent a
    subfolder of its own - named after its color's own layer name:
    "{layerName}_part{N}.obj". The base plate (mesh.meshes' last entry -
    see Mesh._calculateMesh) always uses "base", since it isn't a
    palette entry and so has no name of its own. Returns the list of
    file paths written.

    Every real color needs a name before this can produce a sane result
    (see unnamedColorIndices/duplicateColorNames) - that's enforced by
    the save guard and the export window, not here, so this function
    stays a plain writer rather than a second copy of that validation."""
    os.makedirs(outputDir, exist_ok=True)

    paths = []
    palette = mesh.canvas.palette
    for colorIndex, components in enumerate(mesh.meshes):
        layerName = palette[colorIndex].name if colorIndex < len(palette) else "base"

        for partIndex, triangles in enumerate(components):
            if len(triangles) == 0:
                continue
            filename = f"{layerName}_part{partIndex}.obj"
            path = os.path.join(outputDir, filename)
            writeObj(triangles, path, cellWidth=cellWidth, cellHeight=cellHeight)
            paths.append(path)
    return paths
