import numpy as np

from utils.data.canvas import Canvas
from utils.data.mesh import Mesh
from utils.data.objExport import exportMeshObjs, writeObj
from utils.data.vector import Vector3


def test_write_obj_has_matching_vertex_and_face_counts(tmp_path):
    triangles = [
        Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0),
        Vector3(1, 0, 0), Vector3(1, 1, 0), Vector3(0, 1, 0),
    ]
    path = tmp_path / "square.obj"

    writeObj(triangles, str(path))

    lines = path.read_text().splitlines()
    vLines = [l for l in lines if l.startswith("v ")]
    fLines = [l for l in lines if l.startswith("f ")]
    assert len(vLines) == 6
    assert len(fLines) == 2


def test_write_obj_face_indices_are_valid_and_one_indexed(tmp_path):
    triangles = [Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0)]
    path = tmp_path / "tri.obj"

    writeObj(triangles, str(path))

    faceLine = next(l for l in path.read_text().splitlines() if l.startswith("f "))
    indices = [int(tok) for tok in faceLine.split()[1:]]
    assert indices == [1, 2, 3]


def test_export_mesh_objs_writes_one_file_per_disconnected_component(tmp_path):
    img = np.zeros((4, 8, 3), dtype=np.uint8)
    img[:, :4] = (30, 30, 200)
    img[:, 4:] = (200, 30, 30)
    canvas = Canvas(img)
    canvas.layers[:] = -1
    canvas.layers[0, 0] = 3
    canvas.layers[1, 1] = 3       # same color/height, diagonal, disconnected from the above pair for this test
    canvas.layers[0, 2] = 3       # a separate red pixel

    mesh = Mesh()
    mesh.canvas = canvas
    mesh._calculateMesh()

    paths = exportMeshObjs(mesh, str(tmp_path))

    totalComponents = sum(len(components) for components in mesh.meshes) + len(mesh.baseMesh)
    assert len(paths) == totalComponents
    for path in paths:
        assert path.endswith(".obj")
        content = open(path).read()
        assert content.startswith("# Generated by Plate-A-Pixel")


def test_export_mesh_objs_skips_empty_components(tmp_path):
    class FakeMesh:
        meshes = [[[]], [[Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0)]]]
        baseMesh = [[]]

    paths = exportMeshObjs(FakeMesh(), str(tmp_path))

    assert len(paths) == 1
