import numpy as np

from utils.data.canvas import Canvas
from utils.data.mesh import Mesh
from utils.data.objExport import exportMeshObjs, writeObj
from utils.data.vector import Vector3


def test_write_obj_has_matching_vertex_and_face_counts(tmp_path):
    triangles = [
        Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0),
        Vector3(1, 0, 0), Vector3(1, 1, 0), Vector3(0, 1, 0),
    ]
    path = tmp_path / "square.obj"

    writeObj(triangles, str(path))

    lines = path.read_text().splitlines()
    vLines = [l for l in lines if l.startswith("v ")]
    fLines = [l for l in lines if l.startswith("f ")]
    assert len(vLines) == 6
    assert len(fLines) == 2


def test_write_obj_face_indices_are_valid_and_one_indexed(tmp_path):
    triangles = [Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0)]
    path = tmp_path / "tri.obj"

    writeObj(triangles, str(path))

    faceLine = next(l for l in path.read_text().splitlines() if l.startswith("f "))
    indices = [int(tok) for tok in faceLine.split()[1:]]
    assert indices == [1, 2, 3]


def test_export_mesh_objs_writes_one_file_per_disconnected_component(tmp_path):
    img = np.zeros((4, 8, 3), dtype=np.uint8)
    img[:, :4] = (30, 30, 200)
    img[:, 4:] = (200, 30, 30)
    canvas = Canvas(img)
    canvas.layers[:] = -1
    canvas.layers[0, 0] = 3
    canvas.layers[1, 1] = 3       # same color/height, diagonal, disconnected from the above pair for this test
    canvas.layers[0, 2] = 3       # a separate red pixel

    mesh = Mesh()
    mesh.canvas = canvas
    mesh._calculateMesh()

    paths = exportMeshObjs(mesh, str(tmp_path))

    totalComponents = sum(len(components) for components in mesh.meshes)
    assert len(paths) == totalComponents
    for path in paths:
        assert path.endswith(".obj")
        content = open(path).read()
        assert content.startswith("# Generated by Plate-A-Pixel")


def test_export_mesh_objs_names_each_folder_and_file_after_its_own_rgb_value(tmp_path):
    img = np.zeros((2, 2, 3), dtype=np.uint8)
    img[:] = (30, 30, 200)
    canvas = Canvas(img)
    canvas.layers[:] = -1
    canvas.layers[0, 0] = 3

    mesh = Mesh()
    mesh.canvas = canvas
    mesh._calculateMesh()

    paths = exportMeshObjs(mesh, str(tmp_path))

    blueDir = tmp_path / "30_30_200"
    assert blueDir.is_dir()
    assert any(p.endswith("30_30_200_part0.obj") for p in paths)
    assert (blueDir / "30_30_200_part0.obj").exists()


def test_export_mesh_objs_puts_the_base_plate_in_its_own_folder_never_a_color_folder(tmp_path):
    img = np.zeros((2, 2, 3), dtype=np.uint8)
    img[:] = (30, 30, 200)
    canvas = Canvas(img)
    canvas.layers[:] = -1
    canvas.layers[0, 0] = 3

    mesh = Mesh()
    mesh.canvas = canvas
    mesh._calculateMesh()

    paths = exportMeshObjs(mesh, str(tmp_path))

    baseDir = tmp_path / "base"
    assert baseDir.is_dir()
    assert any(p.endswith("base_part0.obj") for p in paths)
    # never named after a color, and never sharing a folder with one
    assert not any("30_30_200" in p and "base" in p for p in paths)


def test_export_mesh_objs_skips_empty_components(tmp_path):
    class FakeCanvas:
        palette = [(30, 30, 200)]

    class FakeMesh:
        canvas = FakeCanvas()
        meshes = [[[]], [[Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(0, 1, 0)]]]

    paths = exportMeshObjs(FakeMesh(), str(tmp_path))

    assert len(paths) == 1
    assert paths[0].endswith("base_part0.obj")  # index 1 is past the 1-entry palette
